# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/web/" # Location of package manifests
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: "

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/deployment/docker/app/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: "
 
  # Enable version updates for Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: "
