services:
  econumo:
    image: econumo/econumo-ce:latest
    env_file:
      - .env
    ports:
      - "8181:80"
    volumes:
      - db:/var/www/var/db
      #- ./jwt:/var/www/config/jwt
    restart: unless-stopped

    # Example of the healthcheck
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost/_/health-check"]
#      interval: 1m30s
#      timeout: 10s
#      retries: 12
#      start_period: 60s
#      start_interval: 5s

volumes:
  db: