---
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\EconumoToolsBundle\:
    resource: '../../*'
    exclude:
      - '../../tests'
      - '../../**/{Dto,ValueObject,Model,Entity,Exception}/*.php'
      - '../../Domain/{Exception,Traits,Entity,Event}'
      - '../../Domain/{Exception,Traits,Entity,Event}/*.php'
      - '../../Domain/{Exception,Traits,Entity,Event}/**/*.php'

  App\EconumoToolsBundle\Domain\Service\CurrencyRatesLoaderServiceInterface:
    class: \App\EconumoToolsBundle\Infrastructure\OpenExchangeRates\CurrencyRatesLoaderService
    arguments:
      $token: '%env(OPEN_EXCHANGE_RATES_TOKEN)%'
