name: "Build Econumo"

on:
  push:

concurrency:
  group: 'build-econumo'
  cancel-in-progress: true

jobs:
  build-econumo:
    name: Build Econumo
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: 'econumo'

    steps:
      - uses: actions/checkout@v4

      - name: Clone EconumoCloudBundle repository
        uses: actions/checkout@v4
        with:
          repository: econumo/econumo-cloud-bundle
          ref: main
          token: ${{ secrets.BUILD_USER_TOKEN }}
          path: src/EconumoCloudBundle

      - name: Ignore bundles
        run: |
          touch src/EconumoCloudBundle/.disabled

      - name: Build Econumo image for testing
        if: success()
        run: |
          docker build --tag ${DOCKER_IMAGE} --target test -f deployment/docker/app/Dockerfile .

      - name: Test Econumo CE
        if: success()
        run: |
          docker run --volume shared-volume:/var/www/var/db ${DOCKER_IMAGE} bin/console cache:clear --env=test
          docker run --volume shared-volume:/var/www/var/db ${DOCKER_IMAGE} bin/console doctrine:database:create --env=test
          docker run --volume shared-volume:/var/www/var/db ${DOCKER_IMAGE} bin/console doctrine:migration:migrate -n --env=test
          docker run --volume shared-volume:/var/www/var/db ${DOCKER_IMAGE} bin/console doctrine:schema:validate --skip-sync --env=test
          docker run --volume shared-volume:/var/www/var/db ${DOCKER_IMAGE} bin/console doctrine:fixtures:load -n --env=test
          docker run --volume shared-volume:/var/www/var/db --env QASE_ENABLE=${QASE_ENABLE} --env QASE_TOKEN=${QASE_TOKEN} --env QASE_PROJECT=${QASE_PROJECT} ${DOCKER_IMAGE} vendor/bin/codecept run
        env:
          QASE_ENABLE: "false"
          QASE_TOKEN: ${{ secrets.APP_QASE_TOKEN }}
          QASE_PROJECT: "EA"

      - name: Test Econumo Cloud
        if: success()
        run: |
          docker run --volume shared-volume:/var/www/var/db ${DOCKER_IMAGE} rm -f src/EconumoCloudBundle/.disabled
          docker run --volume shared-volume:/var/www/var/db ${DOCKER_IMAGE} bin/console cache:clear --env=test
          docker run --volume shared-volume:/var/www/var/db ${DOCKER_IMAGE} bin/console doctrine:database:create --env=test
          docker run --volume shared-volume:/var/www/var/db ${DOCKER_IMAGE} bin/console doctrine:migration:migrate -n --env=test
          docker run --volume shared-volume:/var/www/var/db ${DOCKER_IMAGE} bin/console doctrine:schema:validate --skip-sync --env=test
          docker run --volume shared-volume:/var/www/var/db ${DOCKER_IMAGE} bin/console doctrine:fixtures:load -n --env=test
          docker run --volume shared-volume:/var/www/var/db --env QASE_ENABLE=${QASE_ENABLE} --env QASE_TOKEN=${QASE_TOKEN} --env QASE_PROJECT=${QASE_PROJECT} ${DOCKER_IMAGE} vendor/bin/codecept run
          docker run --volume shared-volume:/var/www/var/db ${DOCKER_IMAGE} touch src/EconumoCloudBundle/.disabled
        env:
          QASE_ENABLE: "false"
          QASE_TOKEN: ${{ secrets.APP_QASE_TOKEN }}
          QASE_PROJECT: "EA"
