name: "Build MAIN branch"
on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: "frontend-build"
  cancel-in-progress: true

jobs:
  econumo-ce-update-dist:
    uses: ./.github/workflows/embedded-update-dist.yaml
    with:
      ECONUMO_EDITION: "ce"
      REPO_PATH: "econumo/econumo-ce-frontend"
    secrets: inherit

  econumo-cloud-update-dist:
    uses: ./.github/workflows/embedded-update-dist.yaml
    with:
      ECONUMO_EDITION: "cloud"
      REPO_PATH: "econumo/econumo-cloud-frontend"
    secrets: inherit
