---
version: '3.5'

services:
  nginx:
    build:
      context: .
      dockerfile: build/docker/nginx/Dockerfile
      target: prod
    environment:
      - ECONUMO_CONFIG_API_URL="http://localhost:8082"
    ports:
      - ${DOCKER_COMPOSE_PORT_NGINX}:80
